### ISSUE TITLE
Send Mail Process does not work in some cases

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#95]
#### Describe your issue

In some cases, the send mail process does not work anymore. 

On macOS the following error message is thrown: 

```
Error: Sendmail exited with Exit Code 1
```

On Linux, the following exception is thrown: 

```
-- An unhandled exception was caught! Error: --
{ Error: spawn sendmail ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn sendmail',
  path: 'sendmail',
  spawnargs: 
   [ '-i',
     '-f',
     'mailservice@process-engine.io',
     'robin.palkovits@5minds.de' ] }
-- end of unhandled exception stack trace --
```

#### How can others reproduce the issue?
* Try to execute a Process that uses  the send-mail service

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@robpal94  Duplicate?
https://github.com/process-engine/process_engine_runtime/issues/28

**Comment by robpal94** [comment]
The referenced issue only affects windows but I will add these informations to the referenced one.
